apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_USER: YWRtaW4=