apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
data:
  POSTGRES_DB_NAME: url_mapping
  POSTGRES_HOST: postgres